with CTE as (
select
TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
CASE
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2) THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5) THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8) THEN 'SUMMER'
    ELSE 'FALL'
END AS STATION_OF_YEAR,
CASE 
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat', 'Sun') THEN 'WEEKEND'
    ELSE 'BUSINESSDAY'
END AS DAY_TYPE
from {{ source('demo', 'bike') }}
where STARTED_AT != 'started_at'
)

select *
from CTE